app/Http/Controllers/Api/PatientsController.php
app/Http/Controllers/Api/TreatmentsController.php
app/Http/Requests/PatientPageApiRequest.php
app/Http/Requests/TreatmentPageApiRequest.php
resources/js/components/pages/leader/PatientsList.vue
resources/js/components/pages/leader/TreatmentList.vue

Laravelバリデーション追加

---

app/Http/Controllers/Api/TeamsController.php
resources/js/components/pages/staff/SelectRole.vue
routes/api.php

- リーダーボタン押下時のteamsテーブルへpostするAPIを作成
- リーダーとスタッフの選択ボタン設置
- リーダーとスタッフの画面遷移作成

役割選択のAPI作成

---

app/Http/Controllers/Api/UsersController.php
resources/js/components/pages/admin/EditStaff.vue
resources/js/components/pages/admin/StaffList.vue
resources/js/router.js
routes/api.php

- 選択した看護師の情報取得API
- とりあえず名前だけ編集API
- edit-staffにパラメータでuser_idを持たせました

看護師編集API作成

---

app/Http/Controllers/Api/TeamUsersController.php
app/Http/Controllers/Api/TeamsController.php
app/Team.php
app/TeamUser.php
app/User.php
database/migrations/2020_09_04_211051_change_team_user_table.php
database/seeds/TeamUsersTableSeeder.php
database/seeds/TeamsTableSeeder.php
resources/js/components/pages/leader/ScheduleList.vue
resources/js/components/pages/leader/SelectStaff.vue
routes/api.php

チームメンバー登録API

---

app/Http/Controllers/Api/PatientsController.php
app/Http/Requests/PatientPageApiRequest.php
resources/js/components/pages/leader/EditPatient.vue
resources/js/components/pages/leader/PatientsList.vue
resources/js/components/pages/leader/RegistPatient.vue
resources/js/router.js

[更新] 患者一覧から患者編集画面へのリンク

---

resources/js/components/App.vue
resources/js/components/items/FooterComponent.vue
resources/js/components/pages/staff/SelectRole.vue

・見た目ある程度整えました
・＜戻るボタンでログアウトをしたかったができなかった…

役割選択画面整えました

---

app/Http/Controllers/Api/TreatmentsController.php
resources/js/components/pages/leader/EditTreatment.vue
resources/js/components/pages/leader/RegistTreatment.vue

**TreatmentCotroller**
編集する患者取得：editTreatment
処置編集：updateTreatment
をページ遷移する形でデータを取得する方法に変えたので、一部APIの記述を変更しております！
エラーは出てないと思うのですが、変数名がapi.phpのURLに記載のものを使用しているので
実際の内容と違和感あれば変更してください＾＾

[追加] 処置編集ページ / 処置編集・バリデーション（仮）

---

resources/js/components/pages/leader/SelectStaff.vue
routes/api.php

選択したスタッフのidが全て`$request->id`で配列として渡るようになっております。
サーバー側の記述の更新お願いします＾＾

[更新] （リーダー）スタッフ選択 / 選択したスタッフのIDを配列でDBにinsert

---

package-lock.json
package.json
resources/js/components/App.vue
resources/js/components/pages/leader/SelectStaff.vue
resources/js/components/pages/staff/SelectPatients.vue
resources/views/auth/login.blade.php

少し見た目を整えました
＜未了＞
選択後の背景色、idを表示するところを削除、フッター背景色

スタッフ選択画面（仮）

---

resources/js/components/pages/leader/TreatmentList.vue
resources/js/components/pages/staff/SelectPatients.vue

辻ちゃんの作ってくれたスタッフ選択を参考に患者選択もIDを配列で表示するようにしてみました
見た目も同じように整えました
＜未了＞
moment.jsで年齢、入院日から何日、手術日から何日を表示
選択後の背景色、idを表示するところを削除、フッター背景色

患者選択画面もスタッフ選択と同様に選択した患者のIDを配列でDBにinsertっぽくしてみました

---

resources/js/components/App.vue
resources/js/components/pages/staff/SelectPatients.vue

v-stepper追加
moment.jsの部分でエラーが出ていますがとりあえずスルーでお願いします

患者選択画面にステッパー追加

---

app/Http/Controllers/Api/TeamUsersController.php
app/Http/Controllers/Api/TeamsController.php
resources/js/components/pages/leader/ScheduleList.vue
resources/js/components/pages/leader/SelectStaff.vue
resources/js/components/pages/staff/SelectRole.vue
resources/js/router.js
resources/js/store/modules/auth.js
routes/api.php

- 役割選択時のAPIが消滅していたので、復活させた（どっかのコンフリクトで消しちゃったんだと思います笑）
- チームidをURLに持たせました
- ページ遷移をして、問題なく挙動するようにAPIを変更しました

役割選択~予定一覧までのAPI修正

---

public/mix-manifest.json
resources/js/components/pages/staff/RegistTreatmentSchedule.vue

スケジュール登録ステップ2 処置設定でコンフリクトしたv-card記述部分を残したところ、
ページが白紙になってしまったので一旦コメントアウトしました

v-cardの記述部分を一旦コメントアウトしました

---

resources/js/components/items/BirthdayMomentJs.vue
resources/js/components/items/MomentJs.vue
resources/js/components/pages/staff/SelectPatients.vue
routes/api.php

BirthDayMomentJS.Vue：誕生日から年齢を割り出すコンポーネント
MomentJS.Vue：日付のフォーマットを変更するコンポーネント（フォーマットは定まってないので後からいじります〜）
どちらも`:time="〇〇"`で誕生日や日付をStrで渡せば変換されま〜すので、必要なところで使用してください＾＾

[追加]誕生日から年齢を割り出すMomentJSのコンポーネントを追加

---

resources/js/components/pages/staff/RegistTreatmentSchedule.vue

`tratmentSchedule`というオブジェクトに１人の患者に対する処置スケジュールが配列で複数入っております！
そちらの保存処理を記述お願いします！
treatment_nameなど不要要素もあるんですが、表示上必要だったので入れたままですが、
もし問題があれば対処するので教えてください！

[追加]処置スケジュール登録 / 処置登録を保存する記述を追加

---

app/Http/Controllers/Api/SchedulesController.php
app/Schedule.php
resources/js/components/pages/leader/ScheduleList.vue
routes/api.php

- 詳細モーダルから時間だけ更新するようにしました
- リーダー用のスケジュールAPIを追加してます
- ドラッグ&ドロップでは更新させてません（なるはやでやります）
- リーダーによる予定の新規作成（別途APIを作成か、既存のAPIを修正する必要アリ）

スケジュール時間更新処理

---

app/Http/Controllers/Api/SchedulesController.php
resources/js/components/pages/leader/ScheduleList.vue

- ドラック&ドロップでスケジュールのデータ更新を実装
- 新規スケジュール追加処理
- オブジェクトをひっぱって時間変更（これ必要か不明だったので、打ち合わせで相談します）

ドラック&ドロップで更新

---

app/Http/Controllers/Api/SchedulesController.php
resources/js/components/pages/staff/SelectPatients.vue
resources/js/components/pages/staff/SelectRole.vue
resources/js/router.js
routes/api.php

- 新規スケジュール登録API作成
- SelectRole.vueから、スタッフを選択時にAPI発火
- 参照するスケジュールidをパスに付与

schedule登録API作成&パス変更

---

resources/js/components/items/HeaderComponent.vue
resources/js/router.js
resources/js/store/index.js

・ヘッダーの戻るボタンで1つ前の画面に戻る
・ページごとのタイトル反映（未実装ページあり、最後の調整でやりたいと思います）
・ログアウトをアイコンに変更

ヘッダーの1つ前の画面に戻る、タイトル反映の仕組み作り、ログアウトをアイコンに変更

---

resources/js/components/pages/staff/StaffSchedule.vue

表題通りタッチイベントを追加しましたが、修正するかも・・・実機検証したい・・・！
```
@touchstart:event="startDrag"
@touchstart:time="startTime"
@touchmove:time="mouseMove"
@touchendup:time="endDrag"
```

[修正] スタッフスケジュール一覧 / ドラックアンドドロップのスマホ対応

---

resources/js/components/pages/staff/StaffSchedule.vue

細かくpull requestすみません・・・！
完了フラグに応じてタスクのカラーを変更してます！
フラグ変更した際の処理を`/api/schedules/update/`を使用してスケジュールのデータを全て送ってます〜
APIからresで返ってくるデータを元に完了済みのタスクの色が変わる仕様になっているので、
現状動いてないですが、APIとの繋ぎ込みがうまくいけば動くはず〜

[修正]完了タスクのカラー変更

---

resources/js/components/pages/staff/StaffSchedule.vue

APIにデータを持たせるのを失念しておりましたので追加しました！
リアクションいりません〜！

[修正] スタッフスケジュール一覧 / APIにデータを付与

---

app/Http/Controllers/Api/TasksController.php
resources/js/components/pages/staff/RegistTreatmentSchedule.vue
routes/api.php

- スタッフの処置登録APIを変更
- スタッフ選択〜スケジュール登録までちゃんと動くようになりました

スタッフの処置登録API変更

---

resources/js/components/items/HeaderComponent.vue
resources/js/components/pages/staff/PatientSchedule.vue
resources/js/components/pages/staff/StaffSchedule.vue
resources/js/router.js
routes/api.php

- コンポーネント追加
- ルーティング追加
- カレンダー機能実装
- ドラッグ&ドロップで時刻の更新
- 本ページについては、患者間のタスク移動は不可にしてます

患者ごとのスケジュール一覧ページ作成

---

app/Http/Controllers/Api/TasksController.php
resources/js/components/pages/leader/ScheduleList.vue
routes/api.php

- スタッフのスケジュール一覧から、空間クリックで新規タスク登録モーダル表示
- リーダーによるスタッフのタスク登録API追加

リーダーによる新規スケジュール登録実装

---

resources/js/components/App.vue
resources/js/components/items/FooterComponent.vue
resources/js/components/pages/staff/SelectPatients.vue
resources/js/router.js

ヘッダータイトル設定

---

resources/js/components/App.vue
resources/js/components/items/FooterComponent.vue
resources/js/components/pages/staff/RegistSchedule.vue
resources/js/components/pages/staff/RegistTreatmentSchedule.vue
resources/js/components/pages/staff/SelectPatients.vue
resources/js/components/pages/staff/SelectRole.vue
resources/js/components/pages/staff/StaffSchedule.vue
resources/js/router.js

・スタッフページのフッター設定
・スケジュールページのレイアウト整備
※スクロールが上手く動作していないかもしれないので後ほど直します

スタッフフッター設定、その他レイアウト整備

---

database/seeds/TreatmentsTableSeeder.php
resources/js/components/pages/leader/ScheduleList.vue
resources/js/components/pages/staff/PatientSchedule.vue
resources/js/components/pages/staff/RegistSchedule.vue
resources/js/components/pages/staff/StaffSchedule.vue

- 下記ページでタスクに色がつくようになりました
　- スタッフのスケジュール調整
　- スタッフのスケジュール
　- スタッフの患者ごとスケジュール一覧
　- リーダーのスケジュールリスト
- シーダーにカラーコード入れました

カレンダーに処置カラー実装

---

resources/js/components/pages/leader/EditPatient.vue
resources/js/components/pages/leader/PatientsList.vue
resources/js/components/pages/leader/RegistPatient.vue
resources/js/components/pages/staff/RegistTreatmentSchedule.vue
resources/js/components/pages/staff/SelectPatients.vue
resources/js/components/pages/staff/SelectRole.vue
resources/js/components/pages/staff/StaffSchedule.vue

▼スタッフ
・役割選択：ログアウトボタンに変更
・処置スケジュール登録-患者選択：記載内容の精査・バリデーション
・処置スケジュール登録-各患者の処置選択：必須のカラー変更、細かいレイアウト修正
・スケジュール一覧：モーダルのアニメーション、タイトル追加
→レイアウトはあんまりなので、改善の余地あり。
▼リーダー
・患者登録・編集・一覧

＜リーダー＞患者登録周り・＜スタッフ＞スケジュール一覧モーダル

---

resources/js/components/pages/leader/TreatmentList.vue

・タイトル消す
・アイコン消す（メディカル、編集）
・選択した色出してみる
・削除モーダル追加
・追加ボタン（固定）追加 <辻さんの見ましたありがとうございます

処置一覧のスタイル調整

---

resources/js/components/pages/leader/SelectStaff.vue

**やったこと**
・名前だけ表示
・選択中の人数表示(フッター)>辻さん感謝
・色を患者選択に合わせる

スタッフ選択のスタイル調整

---

package-lock.json
package.json
resources/js/components/App.vue
resources/js/components/pages/leader/EditTreatment.vue

**やったこと**
・タイトル消す
・カラーピッカー変更（10種類くらい、グレー無し） 
→npmでvue-swatchesをインストール
・「時間指定が必要」に変更

処置編集の調整、vue-swatchesインストール

---

resources/js/components/pages/staff/RegistSchedule.vue

・説明文追加
・未登録人数をフッターに表示→完了ボタン
・スマホ対応タッチイベントの追加
- vuetifyカレンダーの日付を消すと、時刻が登録されていないタスクも消えてしまうようなので、いったん残してます。（Jootoに記載済み）
UX微妙すぎるので、もうちょい考えたいです。

スケジュール調整ページ修正

---

resources/js/components/App.vue
resources/js/components/items/HeaderComponent.vue
resources/js/components/pages/LogoutCheck.vue
resources/js/router.js

やったこと
・ハンバーガーメニューに引継ぎページとログアウト確認ページ設置

ヘッダー、ドロワー修正

---

resources/js/components/pages/leader/RegistTreatment.vue

**やったこと**
・タイトル消す
・ボタンを[変更]→[登録]
・カラーピッカー調整
辻ちゃんコメントのバグは内容確認中で後ほど直します！

処置登録（バグ以外）調整

---

package-lock.json
package.json
resources/js/components/pages/staff/StaffSchedule.vue

＜やったこと＞
スタッフスケジュール一覧に表示される下記モーダル を調整
- スケジュール詳細
- スケジュールの新規作成
**vue-timepickerのバージョンをあげたのでnpm installお願いします！**

スタッフスケジュール一覧 / モーダルの調整

---

resources/js/components/pages/leader/ScheduleList.vue
resources/js/components/pages/staff/PatientSchedule.vue
resources/js/components/pages/staff/StaffSchedule.vue

＜やったこと＞
下記、ページのモーダルを調整
▼スタッフ
- 患者ごとのスケジュールページ（タスク詳細）
-  スケジュール一覧（新規タスク登録・タスク詳細）
▼リーダー
- スタッフスケジュール（新規タスク登録・タスク詳細）

【スタッフ】患者スケジュール・スケジュール一覧　【リーダー】スタッフスケジュール一覧　モーダルの調整

---

resources/js/components/App.vue
resources/js/components/pages/LogoutCheck.vue
resources/js/components/pages/staff/RegistSchedule.vue
resources/js/components/pages/staff/RegistTreatmentSchedule.vue
resources/js/components/pages/staff/StaffSchedule.vue

やったこと
＜LogoutCheck.vue＞
・ページ内容作成
＜RegistTreatmentSchedule.vue＞
・プルダウンの矢印や文字のずれ修正
・時間選択プルダウンを開いた時にフッター が下に下がるのを修正
・横スクロール禁止追加
＜StaffSchedule.vue＞
・予定追加のモーダルのプルダウンの矢印や文字のずれ修正
＜RegistSchedule.vue＞
・スケジュール調整の決定ボタン修正
（footer-conpのtext-decoration:none;）

ログアウトページ内容作成＆スタッフページcss調整

---

resources/js/components/pages/leader/ScheduleList.vue
resources/js/components/pages/staff/PatientSchedule.vue

患者別スケジュール内のタスク追加実装
